namespace BikeRental_System3.AI.Models
{
    /// <summary>
    /// Represents a single loaded document in the RAG pipeline.
    ///
    /// RAG Pipeline position:
    ///   [LOAD] → Document ← you are here
    ///   [CHUNK] → DocumentChunk (Phase 4.2)
    ///   [EMBED] → float[] vector (Phase 4.3)
    ///   [STORE] → VectorDB record (Phase 4.4)
    ///   [RETRIEVE] → matching chunks (Phase 4.5)
    ///   [INJECT] → {{context}} in prompt (Phase 4.6)
    ///
    /// Why a dedicated model instead of a plain string?
    ///   - Content alone is not enough: metadata enables attribution ("source: rental-policy.pdf")
    ///   - LoadedAt supports cache invalidation (reload if file modified since LoadedAt)
    ///   - Id enables deduplication in the Vector DB (upsert by Id)
    ///   - Title can be shown in the UI when displaying retrieved sources
    ///
    /// Phase 4.2 usage:
    ///   DocumentChunker splits Document.Content into smaller pieces.
    ///   Each chunk inherits: DocumentId, Source, Title for traceback.
    ///
    /// Example (bike-catalog.pdf):
    ///   Id        = "a3f2-..."
    ///   Title     = "Heaven Bike Rental — Bike Catalog"
    ///   FileName  = "bike-catalog.pdf"
    ///   Content   = "Mountain Hawk — Model 2025\nFrame: Aluminum alloy\nGears: 21-speed..."
    ///   Source    = "C:\DocumentStore\bike-catalog.pdf"
    ///   LoadedAt  = 2026-07-07T10:30:00Z
    /// </summary>
    public class Document
    {
        /// <summary>
        /// Globally unique identifier for this document.
        /// Generated by the document loader at load time.
        /// Used as the key when upserting into Vector DB (Phase 4.4).
        /// </summary>
        public string Id { get; init; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Human-readable title for display and prompt attribution.
        ///
        /// Derived from file name: "bike-catalog.pdf" → "bike-catalog"
        /// Phase 4.6: used in context attribution:
        ///   "According to [bike-catalog], the Mountain Hawk costs ₹500/day."
        /// </summary>
        public string Title { get; init; } = string.Empty;

        /// <summary>
        /// The original file name (with extension).
        /// Example: "rental-policy.pdf"
        ///
        /// Used for:
        ///   - Logging ("Loaded rental-policy.pdf, 3 pages, 4,200 chars")
        ///   - Deduplication check (has this file been loaded before?)
        ///   - File type routing (which IDocumentLoader handles this?)
        /// </summary>
        public string FileName { get; init; } = string.Empty;

        /// <summary>
        /// The full extracted plain text content of the document.
        ///
        /// What this is NOT:
        ///   - Not a base64-encoded binary (that's the raw PDF bytes)
        ///   - Not HTML (no tags)
        ///   - Not rich text (no formatting codes)
        ///
        /// What this IS:
        ///   - Plain UTF-8 text extracted by PdfPig
        ///   - Words and sentences separated by spaces
        ///   - Pages separated by newlines
        ///
        /// Phase 4.2: DocumentChunker splits this Content into chunks of ~512 tokens.
        /// Phase 4.3: Each chunk is passed to OpenAI Embeddings API.
        /// </summary>
        public string Content { get; init; } = string.Empty;

        /// <summary>
        /// The absolute file path where this document was loaded from.
        /// Example: "C:\DocumentStore\bike-catalog.pdf"
        ///
        /// Used for:
        ///   - Reload detection (compare File.GetLastWriteTime(Source) to LoadedAt)
        ///   - Debug traceability (which file produced this content?)
        ///   - Phase 4.6: shown in GPT context attribution
        /// </summary>
        public string Source { get; init; } = string.Empty;

        /// <summary>
        /// UTC timestamp when this document was loaded.
        ///
        /// Used for:
        ///   - Cache invalidation: if Source file's last-modified > LoadedAt,
        ///     the document is stale and should be reloaded and re-embedded
        ///   - Audit trail: when was this version of the document ingested?
        /// </summary>
        public DateTime LoadedAt { get; init; } = DateTime.UtcNow;

        /// <summary>
        /// Number of characters in Content.
        /// Convenience property — avoids Content.Length calls everywhere.
        /// Useful for logging: "Loaded 4,200 chars from bike-catalog.pdf"
        /// </summary>
        public int ContentLength => Content.Length;

        /// <summary>
        /// Returns true if the document has non-empty extracted text.
        /// A document without content cannot be chunked or embedded.
        /// Useful for validation and logging in the loader.
        /// </summary>
        public bool HasContent => !string.IsNullOrWhiteSpace(Content);
    }
}
