using System.Text.Json.Serialization;

namespace BikeRental_System3.Models
{
    /// <summary>
    /// Maps the JSON that OpenAI returns after a chat completion request.
    ///
    /// Actual OpenAI response shape (simplified):
    /// {
    ///   "choices": [
    ///     {
    ///       "message": { "role": "assistant", "content": "Hello! ..." },
    ///       "finish_reason": "stop"
    ///     }
    ///   ]
    /// }
    ///
    /// We only map the fields we care about. Unknown fields are ignored automatically.
    /// </summary>
    public class OpenAIChatResponse
    {
        /// <summary>
        /// OpenAI can return multiple choices if n > 1. We always use choices[0].
        /// </summary>
        [JsonPropertyName("choices")]
        public List<OpenAIChoice> Choices { get; set; } = new();
    }

    /// <summary>
    /// A single completion choice from OpenAI.
    /// </summary>
    public class OpenAIChoice
    {
        /// <summary>
        /// The message generated by the AI. We read Message.Content for the reply text.
        /// </summary>
        [JsonPropertyName("message")]
        public OpenAIMessage Message { get; set; } = new();

        /// <summary>
        /// Why the generation stopped. "stop" means a complete response.
        /// Other values: "length" (hit max_tokens), "content_filter" (blocked content).
        /// </summary>
        [JsonPropertyName("finish_reason")]
        public string FinishReason { get; set; } = string.Empty;
    }
}
